apiVersion: v2
name: chat-app
description: A Helm chart for Real-Time Chat Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - chat
  - realtime
  - websocket
  - mern
maintainers:
  - name: Abhishek Kumar
    email: singh.421.aspabhiya@gmail.com
