apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: backend
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.backend.port }}
    targetPort: {{ .Values.service.backend.port }}
    protocol: TCP
