apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secrets
  labels:
    app: chat-app
type: Opaque
stringData:
  JWT_SECRET: "bfvthGagX+snL1qOqCQbB20zjtnuOwnmjtdvXny0QBM="
  CLOUDINARY_CLOUD_NAME: "df3myeurh"
  CLOUDINARY_API_KEY: "149538843919841"
  CLOUDINARY_API_SECRET: "s1Rp2d_YBGUoSQNnDrbnPDvwn8w"
  EMAIL_USER: "singh.421.aspabhiya@gmail.com"
  EMAIL_PASS: "pelposdlitxvlubd"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "SecurePassword123!"