apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secrets
  labels:
    app: chat-app
type: Opaque
stringData:
  JWT_SECRET: "myscretkey"
  CLOUDINARY_CLOUD_NAME: "dwag7vlbn"
  CLOUDINARY_API_KEY: "965893437579976"
  CLOUDINARY_API_SECRET: "gR0RETWuBsAMrldZUF_qLbBvV4I"
  EMAIL_USER: "singh.421.aspabhiya@gmail.com"
  EMAIL_PASS: "puiuahwmneclydux"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "SecurePassword123!"