apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: chat-app
    release: {{ .Release.Name }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.secrets.cloudinary.cloudName | quote }}
  CLOUDINARY_API_KEY: {{ .Values.secrets.cloudinary.apiKey | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.secrets.cloudinary.apiSecret | quote }}
  EMAIL_USER: {{ .Values.secrets.email.user | quote }}
  EMAIL_PASS: {{ .Values.secrets.email.pass | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groq.apiKey | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.google.clientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.google.clientSecret | quote }}
  GOOGLE_CALLBACK_URL: {{ .Values.secrets.google.callbackUrl | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.github.clientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.github.clientSecret | quote }}
  GITHUB_CALLBACK_URL: {{ .Values.secrets.github.callbackUrl | quote }}
